%% Convert noiseless metabolite concentrations into mM based on compartment volume in Costa 2014
% Concentrations and fluxes were also multiplied by 1000 to fix some issues
% with the gurobi solver

fclose('all'); close; clear; clc;

% Original data generated by Copasi
load('costaModel/costaData/costa_k-01_hiRes.mat');

compartment_size = [1; % x_1 glc_Ext
        0.047; % x_2 g6p
        0.047; % x_3 f6p
        0.047; % x_4 fbp
        0.047; % x_5 g3p
        0.047; % x_6 bpg
        0.047; % x_7 pep
        0.047; % x_8 pyr
        1; % x_9 lactate
        0.047; % x_10 acetoin
        1; % x_11 acetoin_Ext
        1; % x_12 2,3-butanediol
        0.047; % x_13 acetCoA
        0.047; % x_14 CoA
        1; % x_15 ethanol
        1; % x_16 formate
        1; % x_17 acetate
        0.047; % x_18 m1p
        0.047; % x_19 mannitol
        1; % x_20 mannitol_Ext
        0.047; % x_21 atp
        0.047; % x_22 adp
        0.047; % x_23 nad
        0.047; % x_24 nadh
        0.047; % x_25 pi
        1; % x_26 pi_Ext
        ];
concMatrix = concMatrix.*compartment_size';
concMatrix = 1000*concMatrix;
fluxMatrix = 1000*fluxMatrix;
x0 = concMatrix(1,:)';

save('costaModel/costaData/costa_k-01_concMol_1000_hiRes.mat');

%% LK-DFBA on noiseless L. lactis data

clear;clc;

wrapper_fitCostaNoiselessSplit('costa_k-01_concMol_1000_hiRes.mat',{'LR','NLR','DR'})
wrapper_fitCostaNoiselessSplit('costa_k-01_concMol_1000_hiRes.mat',{'HP'})

%% LK-DFBA on noisy L. lactis data
% Before using, generate noisy data with driver_genNoisyDatasetsCosta.m

clear;clc;

for nTnoisy = [15 50]
    for CoVnoisy = [5 15] 
        for repnoisy = 1:10
            wrapper_fitCostaNoisySplit(sprintf('costa_k-01_concMol_1000_nT-%03d_cov-%02d_rep-%03d.mat',nTnoisy,CoVnoisy,repnoisy),{'LR','NLR','DR'})
            wrapper_fitCostaNoisySplit(sprintf('costa_k-01_concMol_1000_nT-%03d_cov-%02d_rep-%03d.mat',nTnoisy,CoVnoisy,repnoisy),{'HP'})
        end
    end
end
